include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options

analyzer:
  exclude:
    - "**/*.g.dart"
  errors:
    missing_return: error
    dead_code: warning

linter:
  rules:
    avoid_print: true
    prefer_const_constructors: true
    public_member_api_docs: true
    sort_constructors_first: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_unused_constructor_parameters: true
